<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoDefaultLaunchSettingsFile>True</NoDefaultLaunchSettingsFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsNotAsErrors>NU1901;NU1902;NU1903</WarningsNotAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Infrastructure\**" />
    <Compile Remove="Core\**" />
    <Compile Remove="ConfigServiceLibrary\**" />
    <Compile Remove="tests\**" />
    <EmbeddedResource Remove="Infrastructure\**" />
    <EmbeddedResource Remove="Core\**" />
    <EmbeddedResource Remove="ConfigServiceLibrary\**" />
    <Content Remove="Infrastructure\**" />
    <Content Remove="Core\**" />
    <Content Remove="ConfigServiceLibrary\**" />
    <Content Remove="tests\**" />
    <None Remove="Infrastructure\**" />
    <None Remove="Core\**" />
    <None Remove="ConfigServiceLibrary\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="Core\Core.csproj" />
    <ProjectReference Include="Infrastructure\Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ChatApp.Contracts.Http" />
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
    <PackageReference Include="AspNetCore.HealthChecks.Redis" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.OpenApi" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ChatApp.Server.IntegrationTests" />
  </ItemGroup>

</Project>
