services:
  # 引擎一：PostgreSQL 数据库
  postgres_db:
    image: postgres:latest
    container_name: chatapp_postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=520666
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ChatAppDatabase
    ports:
      - "5432:5432"

  # 引擎二：Garnet 缓存 (微软自研的超高性能 Redis 替代品)
  garnet_cache:
    image: ghcr.io/microsoft/garnet:latest # 🌟 官方的 Garnet 镜像地址
    container_name: chatapp_garnet
    restart: always
    ports:
      - "6379:6379" # 依然监听 6379 端口