<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Infrastructure" />
    <InternalsVisibleTo Include="ChatApp.Server.IntegrationTests" />
  </ItemGroup>

    <ItemGroup>
    </ItemGroup>

</Project>
