// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20260803190520_AddDeletionLeaseToken")]
    partial class AddDeletionLeaseToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChatApp.Realtime.Integration.Outbox.RealtimeIntegrationOutboxItem", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<long>("CreatedAtMs")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at_ms");

                    b.Property<short>("EventType")
                        .HasColumnType("smallint")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("last_error");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("locked_by");

                    b.Property<long?>("LockedUntilMs")
                        .HasColumnType("bigint")
                        .HasColumnName("locked_until_ms");

                    b.Property<long>("NextAttemptAtMs")
                        .HasColumnType("bigint")
                        .HasColumnName("next_attempt_at_ms");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<long?>("PublishedAtMs")
                        .HasColumnType("bigint")
                        .HasColumnName("published_at_ms");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<long>("TargetUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_user_id");

                    b.HasKey("EventId");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("ix_outbox_target_user_id");

                    b.HasIndex("PublishedAtMs", "NextAttemptAtMs");

                    b.HasIndex("TargetUserId", "EventType")
                        .HasDatabaseName("ix_outbox_target_user_event_type");

                    b.ToTable("outbox", "realtime");
                });

            modelBuilder.Entity("Core.Models.Auth.MfaRecoveryCodeClaimEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClaimToken")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<DateTimeOffset>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CodeDigest")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalCodesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RemainingCodesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("State")
                        .HasColumnType("smallint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClaimToken")
                        .IsUnique()
                        .HasDatabaseName("UX_MfaRecoveryCodeClaim_Token");

                    b.HasIndex("State", "ExpiresAt")
                        .HasDatabaseName("IX_MfaRecoveryCodeClaim_State_Expires");

                    b.HasIndex("UserId", "State")
                        .HasDatabaseName("IX_MfaRecoveryCodeClaim_User_State");

                    b.ToTable("T_MfaRecoveryCodeClaim", (string)null);
                });

            modelBuilder.Entity("Core.Models.Email.EmailOutboxItem", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsHtml")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("LeaseToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LockOwner")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(998)
                        .HasColumnType("character varying(998)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("to_address");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("IX_EmailOutbox_IdempotencyKey_Active")
                        .HasFilter("\"IdempotencyKey\" IS NOT NULL AND \"Status\" IN (0, 1, 3)");

                    b.HasIndex("Status", "LockedAt")
                        .HasDatabaseName("IX_EmailOutbox_Status_LockedAt");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("IX_EmailOutbox_Status_NextAttemptAt");

                    b.ToTable("T_EmailOutbox", (string)null);
                });

            modelBuilder.Entity("Core.Models.Export.AccountCleanupDeadLetter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeliveryCount")
                        .HasColumnType("bigint");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PayloadJson")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AccountCleanupDeadLetter_Created");

                    b.HasIndex("EventId", "ReasonCode")
                        .IsUnique()
                        .HasDatabaseName("UX_AccountCleanupDeadLetter_Event_Reason");

                    b.ToTable("T_AccountCleanupDeadLetter", (string)null);
                });

            modelBuilder.Entity("Core.Models.Export.AccountCleanupInboxEntry", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("EventId");

                    b.HasIndex("UserId", "ProcessedAt")
                        .HasDatabaseName("IX_AccountCleanupInbox_User_Processed");

                    b.ToTable("T_AccountCleanupInbox", (string)null);
                });

            modelBuilder.Entity("Core.Models.Export.AccountCleanupSaga", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ReplayCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_AccountCleanupSaga_Status_Created");

                    b.ToTable("T_AccountCleanupSaga", (string)null);
                });

            modelBuilder.Entity("Core.Models.Export.AttachmentBlobDeleteJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AttachmentId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LeaseToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StorageKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("attachment");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("UX_AttachmentBlobDeleteJob_ActiveObjectKey")
                        .HasFilter("\"Status\" IN ('Pending', 'Processing')");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AttachmentBlobDeleteJob_UserId");

                    b.HasIndex("Status", "LeaseExpiresAt")
                        .HasDatabaseName("IX_AttachmentBlobDeleteJob_Status_LeaseExpiresAt");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("IX_AttachmentBlobDeleteJob_Due");

                    b.ToTable("T_AttachmentBlobDeleteJob", (string)null);
                });

            modelBuilder.Entity("Core.Models.Export.AttachmentConfirmSaga", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AttachmentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConfirmedObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LeaseToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("OriginalName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProtectedTicket")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long?>("ScanJobId")
                        .HasColumnType("bigint");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UploaderDeletionEpoch")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId")
                        .IsUnique()
                        .HasDatabaseName("UX_AttachmentConfirmSaga_AttachmentId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AttachmentConfirmSaga_UserId");

                    b.HasIndex("Status", "LeaseExpiresAt")
                        .HasDatabaseName("IX_AttachmentConfirmSaga_LeaseDue");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("IX_AttachmentConfirmSaga_Due");

                    b.ToTable("T_AttachmentConfirmSaga", (string)null);
                });

            modelBuilder.Entity("Core.Models.Export.AttachmentScanAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Allowed")
                        .HasColumnType("boolean");

                    b.Property<string>("AttachmentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EngineName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsTransient")
                        .HasColumnType("boolean");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("ScanJobId")
                        .HasColumnType("bigint");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId", "CreatedAt")
                        .HasDatabaseName("IX_AttachmentScanAudit_Attachment_Created");

                    b.HasIndex("ScanJobId", "CreatedAt")
                        .HasDatabaseName("IX_AttachmentScanAudit_Job_Created");

                    b.ToTable("T_AttachmentScanAudit", (string)null);
                });

            modelBuilder.Entity("Core.Models.Export.AttachmentScanJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AttachmentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LeaseToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("OriginalName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("UploaderDeletionEpoch")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId")
                        .IsUnique()
                        .HasDatabaseName("IX_AttachmentScanJob_ActiveAttachment")
                        .HasFilter("\"Status\" IN ('Pending', 'Processing', 'Finalizing')");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AttachmentScanJob_UserId");

                    b.HasIndex("Status", "LeaseExpiresAt")
                        .HasDatabaseName("IX_AttachmentScanJob_LeaseDue");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("IX_AttachmentScanJob_Due");

                    b.ToTable("T_AttachmentScanJob", (string)null);
                });

            modelBuilder.Entity("Core.Models.Export.AttachmentScanProjection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AttachmentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LeaseToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("OriginalName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("ScanJobId")
                        .HasColumnType("bigint");

                    b.Property<long>("ScanVersion")
                        .HasColumnType("bigint");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceEntityTag")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("UploaderDeletionEpoch")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ScanJobId")
                        .IsUnique()
                        .HasDatabaseName("UX_AttachmentScanProjection_ActiveScanJob")
                        .HasFilter("\"Status\" IN ('Pending', 'Processing')");

                    b.HasIndex("Status", "LeaseExpiresAt")
                        .HasDatabaseName("IX_AttachmentScanProjection_LeaseDue");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("IX_AttachmentScanProjection_Due");

                    b.ToTable("T_AttachmentScanProjection", (string)null);
                });

            modelBuilder.Entity("Core.Models.Export.DataExportJob", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DownloadLeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LeaseToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("ReadyAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_DataExportJob_OneActive")
                        .HasFilter("\"ConsumedAt\" IS NULL AND \"Status\" IN ('Pending', 'Processing', 'Ready')");

                    b.HasIndex("Status", "LeaseUntil", "CreatedAt")
                        .HasDatabaseName("IX_DataExportJob_Claim");

                    b.HasIndex("Status", "NextAttemptAt", "CreatedAt")
                        .HasDatabaseName("IX_DataExportJob_Due");

                    b.HasIndex("UserId", "Status", "CreatedAt")
                        .HasDatabaseName("IX_DataExportJob_User_Status");

                    b.ToTable("T_DataExportJob", (string)null);
                });

            modelBuilder.Entity("Core.Models.Export.JobDeadLetterResolution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("AdminUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Queue")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Queue", "JobId", "CreatedAt")
                        .HasDatabaseName("IX_JobDeadLetterResolution_Queue_Job_Created");

                    b.ToTable("T_JobDeadLetterResolution", (string)null);
                });

            modelBuilder.Entity("Core.Models.Friend.BlockRecord", b =>
                {
                    b.Property<long>("BlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BlockId"));

                    b.Property<DateTime>("BlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("BlockedUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("BlockerId")
                        .HasColumnType("bigint");

                    b.HasKey("BlockId");

                    b.HasIndex("BlockedUserId");

                    b.HasIndex("BlockerId", "BlockedUserId")
                        .IsUnique();

                    b.ToTable("T_BlockRecords", (string)null);
                });

            modelBuilder.Entity("Core.Models.Friend.FriendGroup", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("GroupId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_FriendGroup_User_Default")
                        .HasFilter("\"IsDefault\" = TRUE");

                    b.HasIndex("UserId", "GroupName")
                        .IsUnique()
                        .HasDatabaseName("FriendGroupNameConstraint");

                    b.HasIndex("UserId", "SortOrder")
                        .HasDatabaseName("IX_FriendGroup_UserId_SortOrder");

                    b.ToTable("T_FriendGroup", (string)null);
                });

            modelBuilder.Entity("Core.Models.Friend.FriendRequest", b =>
                {
                    b.Property<long>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RequestId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("RequesterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<long>("TargetUserId")
                        .HasColumnType("bigint");

                    b.HasKey("RequestId");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("IX_FriendRequest_TargetUser");

                    b.HasIndex("RequesterId", "Status");

                    b.HasIndex("RequesterId", "TargetUserId")
                        .IsUnique();

                    b.HasIndex("TargetUserId", "Status");

                    b.ToTable("T_FriendRequests", (string)null);
                });

            modelBuilder.Entity("Core.Models.Friend.UserFriendEntry", b =>
                {
                    b.Property<long>("FriendshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FriendshipId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FriendId")
                        .HasColumnType("bigint");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("FriendshipId");

                    b.HasIndex("FriendId");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId", "FriendId")
                        .IsUnique()
                        .HasDatabaseName("IX_User_Friend_Unique");

                    b.ToTable("T_UserFriendEntry", (string)null);
                });

            modelBuilder.Entity("Core.Models.Identity.ApplicationRoles", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Core.Models.Identity.ApplicationUser", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<short>("AccountState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<bool>("AllowBeSearched")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long>("AvatarVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<DateTimeOffset?>("BanUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeletionAttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeletionDeadLetterAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DeletionEpoch")
                        .HasColumnType("bigint");

                    b.Property<string>("DeletionLastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DeletionLeaseOwner")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DeletionLeaseToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("DeletionLeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionNextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<byte>("FriendRequestPolicy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)1);

                    b.Property<bool>("Gender")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedPendingEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedPendingPhoneNumber")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("NormalizedPhoneNumber")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("NotifyFriendRequests")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("NotifySecurityEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<int>("PasswordHashVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("PendingEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("PendingEmailRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PendingPhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("PendingPhoneRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PendingRecoveryCodesHashJson")
                        .HasColumnType("text");

                    b.Property<string>("PendingTotpSecret")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RecoveryCodesHashJson")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<long>("SecurityVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<string>("Signature")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TotpSecret")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("UserNameChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeletionScheduledAt")
                        .HasDatabaseName("IX_AspNetUsers_DeletionScheduledAt")
                        .HasFilter("\"DeletionScheduledAt\" IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedPendingEmail")
                        .HasDatabaseName("IX_AspNetUsers_NormalizedPendingEmail");

                    b.HasIndex("NormalizedPendingPhoneNumber")
                        .HasDatabaseName("IX_AspNetUsers_NormalizedPendingPhoneNumber");

                    b.HasIndex("NormalizedPhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_AspNetUsers_NormalizedPhoneNumber")
                        .HasFilter("\"NormalizedPhoneNumber\" IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("DeletionScheduledAt", "DeletionNextAttemptAt")
                        .HasDatabaseName("IX_AspNetUsers_DeletionDue");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Core.Models.Identity.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Core.Models.Moderation.UserReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AppealNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("BanUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DedupeKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Detail")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EvidenceBodyPreview")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("EvidenceContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EvidenceSnapshot")
                        .HasColumnType("jsonb");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("ReporterId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReviewedByAdminId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("TargetMessageId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<byte>("TargetType")
                        .HasColumnType("smallint");

                    b.Property<long?>("TargetUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DedupeKey")
                        .IsUnique()
                        .HasDatabaseName("UX_UserReport_DedupeKey")
                        .HasFilter("\"DedupeKey\" IS NOT NULL");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("IX_UserReport_TargetUser");

                    b.HasIndex("Status", "Id")
                        .HasDatabaseName("IX_UserReport_Status_Id");

                    b.HasIndex("ReporterId", "TargetUserId", "TargetMessageId", "CreatedAt")
                        .HasDatabaseName("IX_UserReport_Reporter_Target_Created");

                    b.ToTable("T_UserReport", (string)null);
                });

            modelBuilder.Entity("Core.Models.Notifications.NotificationOutboxItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EmailDeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("InAppDeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LeaseToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LockOwner")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("PreferEmail")
                        .HasColumnType("boolean");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("IX_NotificationOutbox_IdempotencyKey_Active")
                        .HasFilter("\"IdempotencyKey\" IS NOT NULL AND \"Status\" IN (0, 1, 3)");

                    b.HasIndex("Status", "LockedAt")
                        .HasDatabaseName("IX_NotificationOutbox_Status_LockedAt");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("IX_NotificationOutbox_Status_NextAttemptAt");

                    b.ToTable("T_NotificationOutbox", (string)null);
                });

            modelBuilder.Entity("Core.Models.Security.AdminAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("AdminUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long?>("TargetUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("IX_AdminAuditLog_Target");

                    b.HasIndex("AdminUserId", "CreatedAt")
                        .HasDatabaseName("IX_AdminAuditLog_Admin_Created");

                    b.ToTable("T_AdminAuditLog", (string)null);
                });

            modelBuilder.Entity("Core.Models.Security.InAppNotification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<long?>("SourceOutboxId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SourceOutboxId")
                        .IsUnique()
                        .HasDatabaseName("IX_InAppNotification_SourceOutboxId")
                        .HasFilter("\"SourceOutboxId\" IS NOT NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_InAppNotification_UserId_Unread")
                        .HasFilter("\"IsRead\" = FALSE");

                    b.HasIndex("UserId", "Id")
                        .HasDatabaseName("IX_InAppNotification_UserId_Id");

                    b.ToTable("T_InAppNotification", (string)null);
                });

            modelBuilder.Entity("Core.Models.Security.LoginAuditOutboxItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<short>("EventType")
                        .HasColumnType("smallint");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LeaseToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Location")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Status", "LeaseExpiresAt")
                        .HasDatabaseName("IX_LoginAuditOutbox_Status_LeaseExpiresAt");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("IX_LoginAuditOutbox_Status_NextAttemptAt");

                    b.ToTable("T_LoginAuditOutbox", (string)null);
                });

            modelBuilder.Entity("Core.Models.Security.ModerationSessionRevocationOutboxItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpectedBanUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExpectedSecurityVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LeaseToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SourceReportId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SourceReportId")
                        .IsUnique()
                        .HasDatabaseName("UX_ModerationSessionRevocationOutbox_SourceReportId");

                    b.HasIndex("Status", "LeaseExpiresAt")
                        .HasDatabaseName("IX_ModerationSessionRevocationOutbox_Status_LeaseExpiresAt");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("IX_ModerationSessionRevocationOutbox_Status_NextAttemptAt");

                    b.ToTable("T_ModerationSessionRevocationOutbox", (string)null);
                });

            modelBuilder.Entity("Core.Models.Security.SecurityEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<short>("EventType")
                        .HasColumnType("smallint");

                    b.Property<string>("Location")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long?>("SourceLoginAuditOutboxId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SourceLoginAuditOutboxId")
                        .IsUnique()
                        .HasDatabaseName("UX_SecurityEvent_LoginAuditOutbox")
                        .HasFilter("\"SourceLoginAuditOutboxId\" IS NOT NULL");

                    b.HasIndex("UserId", "Id")
                        .HasDatabaseName("IX_SecurityEvent_UserId_Id");

                    b.ToTable("T_SecurityEvent", (string)null);
                });

            modelBuilder.Entity("Core.Models.Security.SecurityOperationGrant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GrantHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PayloadHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte>("State")
                        .IsConcurrencyToken()
                        .HasColumnType("smallint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GrantHash")
                        .IsUnique()
                        .HasDatabaseName("UX_SecurityOperationGrant_Hash");

                    b.HasIndex("UserId", "State", "ExpiresAt")
                        .HasDatabaseName("IX_SecurityOperationGrant_User_State_Expires");

                    b.ToTable("T_SecurityOperationGrant", (string)null);
                });

            modelBuilder.Entity("Core.Models.Security.SecuritySessionRevocationOutboxItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("EventType")
                        .HasColumnType("smallint");

                    b.Property<string>("ExceptDeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ExpectedSecurityVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LeaseToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RevokeTrustedDevices")
                        .HasColumnType("boolean");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Status", "LeaseExpiresAt")
                        .HasDatabaseName("IX_SecuritySessionRevocationOutbox_Status_LeaseExpiresAt");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("IX_SecuritySessionRevocationOutbox_Status_NextAttemptAt");

                    b.ToTable("T_SecuritySessionRevocationOutbox", (string)null);
                });

            modelBuilder.Entity("Core.Models.Security.TrustedDevice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DeviceIdHint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SecurityVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("TrustedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_TrustedDevice_TokenHash");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("IX_TrustedDevice_User_Expires");

                    b.ToTable("T_TrustedDevice", (string)null);
                });

            modelBuilder.Entity("Core.Models.Auth.MfaRecoveryCodeClaimEntity", b =>
                {
                    b.HasOne("Core.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Models.Friend.BlockRecord", b =>
                {
                    b.HasOne("Core.Models.Identity.ApplicationUser", "BlockedUser")
                        .WithMany()
                        .HasForeignKey("BlockedUserId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.HasOne("Core.Models.Identity.ApplicationUser", "Blocker")
                        .WithMany()
                        .HasForeignKey("BlockerId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.Navigation("BlockedUser");

                    b.Navigation("Blocker");
                });

            modelBuilder.Entity("Core.Models.Friend.FriendGroup", b =>
                {
                    b.HasOne("Core.Models.Identity.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Core.Models.Friend.FriendRequest", b =>
                {
                    b.HasOne("Core.Models.Identity.ApplicationUser", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.HasOne("Core.Models.Identity.ApplicationUser", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.Navigation("Requester");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("Core.Models.Friend.UserFriendEntry", b =>
                {
                    b.HasOne("Core.Models.Identity.ApplicationUser", "Friend")
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.HasOne("Core.Models.Friend.FriendGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.HasOne("Core.Models.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.Navigation("Friend");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Models.Identity.UserRole", b =>
                {
                    b.HasOne("Core.Models.Identity.ApplicationRoles", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Models.Security.SecurityOperationGrant", b =>
                {
                    b.HasOne("Core.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
