using Infrastructure.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations;

/// <summary>
/// Keeps the immutable scan audit history in fixed hash partitions. The
/// application model remains unchanged; PostgreSQL routes inserts by Id and
/// the retention worker still deletes by indexed CreatedAt in bounded batches.
/// This avoids a single ever-growing heap/index while preserving the existing
/// audit write contract and primary-key semantics.
/// </summary>
[DbContext(typeof(UserDbContext))]
[Migration("20260804120000_PartitionAttachmentScanAudit")]
public partial class PartitionAttachmentScanAudit : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            ALTER TABLE IF EXISTS "T_AttachmentScanAudit"
                RENAME TO "T_AttachmentScanAudit_PartitionedLegacy";

            CREATE SEQUENCE "T_AttachmentScanAudit_Id_seq_partitioned";

            CREATE TABLE "T_AttachmentScanAudit" (
                "Id" bigint NOT NULL DEFAULT nextval('"T_AttachmentScanAudit_Id_seq_partitioned"'::regclass),
                "ScanJobId" bigint NOT NULL,
                "AttachmentId" character varying(64) NOT NULL,
                "ObjectKey" character varying(512) NOT NULL,
                "UserId" bigint NOT NULL,
                "AttemptCount" integer NOT NULL,
                "ContentType" character varying(128),
                "SizeBytes" bigint NOT NULL,
                "EngineName" character varying(128) NOT NULL,
                "EngineVersion" character varying(128) NOT NULL,
                "Verdict" character varying(32) NOT NULL,
                "Allowed" boolean NOT NULL,
                "IsTransient" boolean NOT NULL,
                "Reason" character varying(500),
                "CreatedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_T_AttachmentScanAudit_Partitioned" PRIMARY KEY ("Id")
            ) PARTITION BY HASH ("Id");

            ALTER SEQUENCE "T_AttachmentScanAudit_Id_seq_partitioned"
                OWNED BY "T_AttachmentScanAudit"."Id";

            DO $partition$
            BEGIN
                FOR i IN 0..15 LOOP
                    EXECUTE format(
                        'CREATE TABLE "T_AttachmentScanAudit_p%s" PARTITION OF "T_AttachmentScanAudit" FOR VALUES WITH (MODULUS 16, REMAINDER %s)',
                        i,
                        i);
                END LOOP;
            END $partition$;

            INSERT INTO "T_AttachmentScanAudit" (
                "Id", "ScanJobId", "AttachmentId", "ObjectKey", "UserId",
                "AttemptCount", "ContentType", "SizeBytes", "EngineName",
                "EngineVersion", "Verdict", "Allowed", "IsTransient", "Reason", "CreatedAt")
            SELECT "Id", "ScanJobId", "AttachmentId", "ObjectKey", "UserId",
                   "AttemptCount", "ContentType", "SizeBytes", "EngineName",
                   "EngineVersion", "Verdict", "Allowed", "IsTransient", "Reason", "CreatedAt"
            FROM "T_AttachmentScanAudit_PartitionedLegacy";

            SELECT setval(
                '"T_AttachmentScanAudit_Id_seq_partitioned"'::regclass,
                COALESCE(MAX("Id"), 1),
                MAX("Id") IS NOT NULL)
            FROM "T_AttachmentScanAudit";

            DROP TABLE "T_AttachmentScanAudit_PartitionedLegacy";

            ALTER TABLE "T_AttachmentScanAudit"
                RENAME CONSTRAINT "PK_T_AttachmentScanAudit_Partitioned"
                TO "PK_T_AttachmentScanAudit";

            CREATE INDEX "IX_AttachmentScanAudit_Attachment_Created"
                ON "T_AttachmentScanAudit" ("AttachmentId", "CreatedAt");
            CREATE INDEX "IX_AttachmentScanAudit_Job_Created"
                ON "T_AttachmentScanAudit" ("ScanJobId", "CreatedAt");
            CREATE INDEX "IX_AttachmentScanAudit_Created"
                ON "T_AttachmentScanAudit" ("CreatedAt");
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            ALTER TABLE "T_AttachmentScanAudit"
                RENAME TO "T_AttachmentScanAudit_PartitionedLegacy";

            CREATE TABLE "T_AttachmentScanAudit" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "ScanJobId" bigint NOT NULL,
                "AttachmentId" character varying(64) NOT NULL,
                "ObjectKey" character varying(512) NOT NULL,
                "UserId" bigint NOT NULL,
                "AttemptCount" integer NOT NULL,
                "ContentType" character varying(128),
                "SizeBytes" bigint NOT NULL,
                "EngineName" character varying(128) NOT NULL,
                "EngineVersion" character varying(128) NOT NULL,
                "Verdict" character varying(32) NOT NULL,
                "Allowed" boolean NOT NULL,
                "IsTransient" boolean NOT NULL,
                "Reason" character varying(500),
                "CreatedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_T_AttachmentScanAudit" PRIMARY KEY ("Id")
            );

            INSERT INTO "T_AttachmentScanAudit" (
                "Id", "ScanJobId", "AttachmentId", "ObjectKey", "UserId",
                "AttemptCount", "ContentType", "SizeBytes", "EngineName",
                "EngineVersion", "Verdict", "Allowed", "IsTransient", "Reason", "CreatedAt")
            SELECT "Id", "ScanJobId", "AttachmentId", "ObjectKey", "UserId",
                   "AttemptCount", "ContentType", "SizeBytes", "EngineName",
                   "EngineVersion", "Verdict", "Allowed", "IsTransient", "Reason", "CreatedAt"
            FROM "T_AttachmentScanAudit_PartitionedLegacy";

            SELECT setval(
                pg_get_serial_sequence('"T_AttachmentScanAudit"', 'Id')::regclass,
                COALESCE(MAX("Id"), 1),
                MAX("Id") IS NOT NULL)
            FROM "T_AttachmentScanAudit";

            DROP TABLE "T_AttachmentScanAudit_PartitionedLegacy";
            DROP SEQUENCE IF EXISTS "T_AttachmentScanAudit_Id_seq_partitioned";

            CREATE INDEX "IX_AttachmentScanAudit_Attachment_Created"
                ON "T_AttachmentScanAudit" ("AttachmentId", "CreatedAt");
            CREATE INDEX "IX_AttachmentScanAudit_Job_Created"
                ON "T_AttachmentScanAudit" ("ScanJobId", "CreatedAt");
            """);
    }
}
