using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class P1RelationshipModerationPhoneAvatar : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Earlier versions truncated the serialized evidence string. Do
            // not let one malformed historical row abort the schema upgrade;
            // retain the report and let the new evidence-detail path return
            // null for that legacy snapshot.
            migrationBuilder.Sql(
                "UPDATE \"T_UserReport\" SET \"EvidenceSnapshot\" = NULL " +
                "WHERE \"EvidenceSnapshot\" IS NOT NULL " +
                "AND NOT pg_input_is_valid(\"EvidenceSnapshot\", 'jsonb');");

            // Npgsql cannot infer the text -> jsonb cast when executing an
            // ALTER COLUMN TYPE generated by AlterColumn. The cleanup above
            // deliberately turns malformed legacy snapshots into NULL; the
            // explicit USING clause then preserves every valid JSON snapshot.
            migrationBuilder.Sql(
                "ALTER TABLE \"T_UserReport\" " +
                "ALTER COLUMN \"EvidenceSnapshot\" TYPE jsonb " +
                "USING \"EvidenceSnapshot\"::jsonb;");

            migrationBuilder.AddColumn<string>(
                name: "DedupeKey",
                table: "T_UserReport",
                type: "character varying(256)",
                maxLength: 256,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "EvidenceBodyPreview",
                table: "T_UserReport",
                type: "character varying(4000)",
                maxLength: 4000,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "EvidenceContentHash",
                table: "T_UserReport",
                type: "character varying(128)",
                maxLength: 128,
                nullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "PhoneNumber",
                table: "AspNetUsers",
                type: "character varying(32)",
                maxLength: 32,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true);

            migrationBuilder.AddColumn<long>(
                name: "AvatarVersion",
                table: "AspNetUsers",
                type: "bigint",
                nullable: false,
                defaultValue: 1L);

            migrationBuilder.AddColumn<byte>(
                name: "FriendRequestPolicy",
                table: "AspNetUsers",
                type: "smallint",
                nullable: false,
                defaultValue: (byte)1);

            migrationBuilder.AddColumn<string>(
                name: "NormalizedPendingPhoneNumber",
                table: "AspNetUsers",
                type: "character varying(16)",
                maxLength: 16,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "NormalizedPhoneNumber",
                table: "AspNetUsers",
                type: "character varying(16)",
                maxLength: 16,
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "NotifyFriendRequests",
                table: "AspNetUsers",
                type: "boolean",
                nullable: false,
                defaultValue: true);

            migrationBuilder.AddColumn<string>(
                name: "PendingPhoneNumber",
                table: "AspNetUsers",
                type: "character varying(32)",
                maxLength: 32,
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "PendingPhoneRequestedAt",
                table: "AspNetUsers",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "T_BlockRecords",
                columns: table => new
                {
                    BlockId = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    BlockerId = table.Column<long>(type: "bigint", nullable: false),
                    BlockedUserId = table.Column<long>(type: "bigint", nullable: false),
                    BlockedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_T_BlockRecords", x => x.BlockId);
                    table.ForeignKey(
                        name: "FK_T_BlockRecords_AspNetUsers_BlockedUserId",
                        column: x => x.BlockedUserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK_T_BlockRecords_AspNetUsers_BlockerId",
                        column: x => x.BlockerId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateTable(
                name: "T_FriendGroup",
                columns: table => new
                {
                    GroupId = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    UserId = table.Column<long>(type: "bigint", nullable: false),
                    GroupName = table.Column<string>(type: "text", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    SortOrder = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    IsDefault = table.Column<bool>(type: "boolean", nullable: false, defaultValue: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_T_FriendGroup", x => x.GroupId);
                    table.ForeignKey(
                        name: "FK_T_FriendGroup_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateTable(
                name: "T_FriendRequests",
                columns: table => new
                {
                    RequestId = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    RequesterId = table.Column<long>(type: "bigint", nullable: false),
                    TargetUserId = table.Column<long>(type: "bigint", nullable: false),
                    Message = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    Status = table.Column<byte>(type: "smallint", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    RespondedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_T_FriendRequests", x => x.RequestId);
                    table.ForeignKey(
                        name: "FK_T_FriendRequests_AspNetUsers_RequesterId",
                        column: x => x.RequesterId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK_T_FriendRequests_AspNetUsers_TargetUserId",
                        column: x => x.TargetUserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateTable(
                name: "T_UserFriendEntry",
                columns: table => new
                {
                    FriendshipId = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    UserId = table.Column<long>(type: "bigint", nullable: false),
                    FriendId = table.Column<long>(type: "bigint", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    IsDeleted = table.Column<bool>(type: "boolean", nullable: false),
                    DeletedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    Note = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    GroupId = table.Column<int>(type: "integer", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_T_UserFriendEntry", x => x.FriendshipId);
                    table.ForeignKey(
                        name: "FK_T_UserFriendEntry_AspNetUsers_FriendId",
                        column: x => x.FriendId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK_T_UserFriendEntry_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK_T_UserFriendEntry_T_FriendGroup_GroupId",
                        column: x => x.GroupId,
                        principalTable: "T_FriendGroup",
                        principalColumn: "GroupId");
                });

            migrationBuilder.CreateIndex(
                name: "UX_UserReport_DedupeKey",
                table: "T_UserReport",
                column: "DedupeKey",
                unique: true,
                filter: "\"DedupeKey\" IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_AspNetUsers_NormalizedPendingPhoneNumber",
                table: "AspNetUsers",
                column: "NormalizedPendingPhoneNumber");

            migrationBuilder.CreateIndex(
                name: "UX_AspNetUsers_NormalizedPhoneNumber",
                table: "AspNetUsers",
                column: "NormalizedPhoneNumber",
                unique: true,
                filter: "\"NormalizedPhoneNumber\" IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_T_BlockRecords_BlockedUserId",
                table: "T_BlockRecords",
                column: "BlockedUserId");

            migrationBuilder.CreateIndex(
                name: "IX_T_BlockRecords_BlockerId_BlockedUserId",
                table: "T_BlockRecords",
                columns: new[] { "BlockerId", "BlockedUserId" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "FriendGroupNameConstraint",
                table: "T_FriendGroup",
                columns: new[] { "UserId", "GroupName" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_FriendGroup_UserId_SortOrder",
                table: "T_FriendGroup",
                columns: new[] { "UserId", "SortOrder" });

            migrationBuilder.CreateIndex(
                name: "UX_FriendGroup_User_Default",
                table: "T_FriendGroup",
                column: "UserId",
                unique: true,
                filter: "\"IsDefault\" = TRUE");

            migrationBuilder.CreateIndex(
                name: "IX_FriendRequest_TargetUser",
                table: "T_FriendRequests",
                column: "TargetUserId");

            migrationBuilder.CreateIndex(
                name: "IX_T_FriendRequests_RequesterId_Status",
                table: "T_FriendRequests",
                columns: new[] { "RequesterId", "Status" });

            migrationBuilder.CreateIndex(
                name: "IX_T_FriendRequests_RequesterId_TargetUserId",
                table: "T_FriendRequests",
                columns: new[] { "RequesterId", "TargetUserId" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_T_FriendRequests_TargetUserId_Status",
                table: "T_FriendRequests",
                columns: new[] { "TargetUserId", "Status" });

            migrationBuilder.CreateIndex(
                name: "IX_T_UserFriendEntry_FriendId",
                table: "T_UserFriendEntry",
                column: "FriendId");

            migrationBuilder.CreateIndex(
                name: "IX_T_UserFriendEntry_GroupId",
                table: "T_UserFriendEntry",
                column: "GroupId");

            migrationBuilder.CreateIndex(
                name: "IX_User_Friend_Unique",
                table: "T_UserFriendEntry",
                columns: new[] { "UserId", "FriendId" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "T_BlockRecords");

            migrationBuilder.DropTable(
                name: "T_FriendRequests");

            migrationBuilder.DropTable(
                name: "T_UserFriendEntry");

            migrationBuilder.DropTable(
                name: "T_FriendGroup");

            migrationBuilder.DropIndex(
                name: "UX_UserReport_DedupeKey",
                table: "T_UserReport");

            migrationBuilder.DropIndex(
                name: "IX_AspNetUsers_NormalizedPendingPhoneNumber",
                table: "AspNetUsers");

            migrationBuilder.DropIndex(
                name: "UX_AspNetUsers_NormalizedPhoneNumber",
                table: "AspNetUsers");

            migrationBuilder.DropColumn(
                name: "DedupeKey",
                table: "T_UserReport");

            migrationBuilder.DropColumn(
                name: "EvidenceBodyPreview",
                table: "T_UserReport");

            migrationBuilder.DropColumn(
                name: "EvidenceContentHash",
                table: "T_UserReport");

            migrationBuilder.DropColumn(
                name: "AvatarVersion",
                table: "AspNetUsers");

            migrationBuilder.DropColumn(
                name: "FriendRequestPolicy",
                table: "AspNetUsers");

            migrationBuilder.DropColumn(
                name: "NormalizedPendingPhoneNumber",
                table: "AspNetUsers");

            migrationBuilder.DropColumn(
                name: "NormalizedPhoneNumber",
                table: "AspNetUsers");

            migrationBuilder.DropColumn(
                name: "NotifyFriendRequests",
                table: "AspNetUsers");

            migrationBuilder.DropColumn(
                name: "PendingPhoneNumber",
                table: "AspNetUsers");

            migrationBuilder.DropColumn(
                name: "PendingPhoneRequestedAt",
                table: "AspNetUsers");

            migrationBuilder.Sql(
                "ALTER TABLE \"T_UserReport\" " +
                "ALTER COLUMN \"EvidenceSnapshot\" TYPE character varying(4000) " +
                "USING \"EvidenceSnapshot\"::text;");

            migrationBuilder.AlterColumn<string>(
                name: "PhoneNumber",
                table: "AspNetUsers",
                type: "text",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "character varying(32)",
                oldMaxLength: 32,
                oldNullable: true);
        }
    }
}
