<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Messaging\" />
    </ItemGroup>

    <ItemGroup>
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AWSSDK.S3" />
      <PackageReference Include="BCrypt.Net-Next" />
      <PackageReference Include="MailKit" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="NLog.Extensions.Logging" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
      <PackageReference Include="Otp.NET" />
      <PackageReference Include="SixLabors.ImageSharp" />
      <PackageReference Include="StackExchange.Redis" />
      <PackageReference Include="TSID.Creator.NET" />
      <PackageReference Include="UAParser.Core" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Core\Core.csproj" />
      <ProjectReference Include="$(RealtimeSourcePath)\ChatApp.Realtime.Integration\ChatApp.Realtime.Integration.csproj">
        <SetConfiguration>Configuration=$(Configuration)</SetConfiguration>
        <SetPlatform>Platform=AnyCPU</SetPlatform>
      </ProjectReference>
    </ItemGroup>

    <ItemGroup>
      <InternalsVisibleTo Include="ChatApp.Server.IntegrationTests" />
    </ItemGroup>

</Project>
